spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/persondb
    username: myuser
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect