apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
data:
  userlist.txt: |
    "myuser" ""
  pgbouncer.ini: |
    [databases]
    mydb = host=postgres port=5432 dbname=mydb

    [pgbouncer]
    listen_port = 6432
    listen_addr = 0.0.0.0
    auth_type = trust
    auth_file = /etc/pgbouncer/userlist.txt
    admin_users = myuser
    pool_mode = session
    max_client_conn = 100
    default_pool_size = 20